=== AndresIzquierdoBrito/DAW-LND/Unidad 4 - XML/Schema/Ejercicios esquemas/Ejercicios/Ejercicio 1/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellidos" type="xs:string" />
                            <xs:element name="nota">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:fractionDigits value="2"/>
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"/>
                                        <xs:maxInclusive value="99"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="dni" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{8}[A-Z]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AndresIzquierdoBrito/DAW-LND/Unidad 4 - XML/Schema/Ejercicios esquemas/Ejercicios/Ejercicio 1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio1.xsd">
    <alumno dni="99887766X">
        <nombre>Dario</nombre>
        <apellidos>Fernández Álvarez</apellidos>
        <nota>3.50</nota>
    </alumno>
    <alumno dni="11223344A">
        <nombre>Dario</nombre>
        <apellidos>Fernández Álvarez</apellidos>
        <nota>6.70</nota>
    </alumno>
    <alumno dni="11223344A">
        <nombre>Dario</nombre>
        <apellidos>Fernández Álvarez</apellidos>
        <nota>8.25</nota>
    </alumno>
</alumnos>
